version: '3.7'
#test
services:
#  gradko-db:
#    image: postgres:12
#
#    restart: unless-stopped
#
#    volumes:
#      - gradko_postgres_data:/var/lib/postgresql/data/
    env_file:
      - /home/ubuntu/webhooks/scripts/.env.dev
#    ports:
#      - 5432:5432
  django_back:
    build: .
#    secrets:
#      - SECRET_KEY
#      - PG_NAME
#      - PG_USR
#      - PG_PASSWORD
#      - PG_SERVER
#      - PG_PORT
    restart: unless-stopped

#    depends_on:
#      - gradko-db
#    command: python /usr/src/app/gradko/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app/
    ports:
      - 8888:8888
#    env_file:
#      - ./env.dev
#
#
#
#volumes:
#  gradko_postgres_data:
