# Generated by Django 4.0.3 on 2022-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookingtechnology',
            options={'verbose_name': 'Cooking Technology', 'verbose_name_plural': 'Cooking Technology'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.baseingredients'),
        ),
    ]
